# Generated by Django 4.2.6 on 2023-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
