# Generated by Django 4.2.6 on 2023-10-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(default='stock.jpeg', upload_to='task_images'),
        ),
    ]
