# Generated by Django 4.2.6 on 2023-10-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, default='media/stock.jpg', null=True, upload_to='media/task_images'),
        ),
    ]
