# Generated by Django 4.2.6 on 2023-10-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, default='stock.jpg', null=True, upload_to='task_images'),
        ),
    ]
